service: auction-service
#app: your-app-name
#org: your-org-name

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - ${file(infra/AuctionsTableIAM.yml):AuctionsTableIAM}

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  Resources:
    AuctionsTable: ${file(infra/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handler.createAuction
    events:
      - httpApi:
          path: /auction
          method: POST